/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_byteandahalf_genericlauncher_NativeHandler */

#ifndef _Included_com_byteandahalf_genericlauncher_NativeHandler
#define _Included_com_byteandahalf_genericlauncher_NativeHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_byteandahalf_genericlauncher_NativeHandler
 * Method:    nativeSetupHooks
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_byteandahalf_genericlauncher_NativeHandler_nativeSetupHooks
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
